language: node_js
node_js:
  - "11.0"
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
  - npm install gulp
  - npm install
jobs:
  include:
    - stage: lint
      script: ng lint
    - stage: build
      script:
        - ng build --prod --base-href /
        - gulp purifyCSS
    - stage: deploy
      deploy:
        skip_cleanup: true
        provider: firebase
        token:
          secure: $FIREBASE_TOKEN
