language: node_js
node_js:
  - "11.0"
sudo: required
install:
  - npm install -g @angular/cli
  - npm install gulp
  - npm install
script:
  - sed -i \"s/appVersion: '[0-9]\+\.[0-9]\+\.[0-9]'\+/appVersion: '$VERSAO_TAG'/\" ./src/environments/environment.prod.ts
  - ng lint
  - ng build --prod --base-href /
  - gulp purifyCSS
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master
    tags: true
