language: node_js
node_js:
  - "lts/*"
sudo: required
install:
  - npm install -g @angular/cli
  - npm install gulp
  - npm install
before_script:
  - chmod -R +x ./ci/
  - "./ci/version_control"
script:
  - ng lint
  - ng build --prod --base-href /
  - gulp purifyCSS
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  on:
    branch: master
    tags: true
