language: node_js
node_js:
- '11.0'
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
- npm install gulp
script:
 - npm install
 - ng lint
 - ng build --prod 
 - gulp purifyCSS
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN